# Generated by Django 2.2.5 on 2019-09-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='offertype',
            field=models.BooleanField(default=False),
        ),
    ]
