# Generated by Django 2.2.5 on 2019-09-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
    ]
