# Generated by Django 2.2.5 on 2019-09-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
