# Generated by Django 2.2.5 on 2019-09-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_auto_20190915_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=35)),
            ],
        ),
    ]
