# Generated by Django 2.2.5 on 2019-09-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
