# Generated by Django 2.2.5 on 2019-09-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='menulink',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
