# Generated by Django 2.2.5 on 2019-09-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poletopole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=30)),
                ('Background_Image', models.ImageField(upload_to='pics/home')),
                ('Video_URL', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='home',
        ),
    ]
