# Generated by Django 2.2.5 on 2019-09-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poletopole', '0002_auto_20190917_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeVideo',
            new_name='HomepageVideo',
        ),
    ]
