# Generated by Django 2.2.5 on 2019-09-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poletopole', '0003_auto_20190917_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomepageVideo',
        ),
    ]
