# Generated by Django 2.2.5 on 2019-09-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poletopole', '0005_homepagevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepagepopulardestionatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50)),
                ('Description', models.CharField(blank=True, max_length=50)),
                ('Destination_Image', models.ImageField(upload_to='pics/home')),
                ('Destination_Price', models.IntegerField()),
                ('Destination_Placename', models.CharField(max_length=20)),
            ],
        ),
    ]
