# Generated by Django 2.2.5 on 2019-09-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poletopole', '0006_homepagepopulardestionatio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homepagepopulardestionatio',
            new_name='Homepagepopulardestionation',
        ),
    ]
