# Generated by Django 2.2.5 on 2019-09-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poletopole', '0007_auto_20190917_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagepopulardestionation',
            name='Pageurl',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
