# Generated by Django 2.2.5 on 2019-09-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poletopole', '0008_homepagepopulardestionation_pageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSpecialOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=50)),
                ('Description', models.CharField(blank=True, max_length=50)),
                ('Destination_Image', models.ImageField(upload_to='pics/home')),
                ('Destination_Placename', models.CharField(max_length=20)),
                ('Destination_Subject', models.CharField(max_length=20)),
            ],
        ),
    ]
